

#ifdef _MSC_VER
#pragma warning( disable : 4018 4065 4146 4244 4251 4267 4305 4307 4309 4334 4355 4506 4800 4996)
#endif  // _MSC_VER

    // /wd4018 # 'expression' : signed/unsigned mismatch
    // /wd4065 # switch statement contains 'default' but no 'case' labels
    // /wd4146 # unary minus operator applied to unsigned type, result still unsigned
    // /wd4244 # 'conversion' conversion from 'type1' to 'type2', possible loss of data
    // /wd4251 # 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
    // /wd4267 # 'var' : conversion from 'size_t' to 'type', possible loss of data
    // /wd4305 # 'identifier' : truncation from 'type1' to 'type2'
    // /wd4307 # 'operator' : integral constant overflow
    // /wd4309 # 'conversion' : truncation of constant value
    // /wd4334 # 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
    // /wd4355 # 'this' : used in base member initializer list
    // /wd4506 # no definition for inline function 'function'
    // /wd4800 # 'type' : forcing value to bool 'true' or 'false' (performance warning)
    // /wd4996 # The compiler encountered a deprecated declaration.